// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}

interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
}

type DebugLogLevel =
  | "info"
  | "success"
  | "warn"
  | "error"
  | "debug"
  | "route"
  | "ipc"
  | "updater"
  | "perf"
  | "network"
  | "state"
  | "lifecycle";

interface DebugAPI {
  log: (level: DebugLogLevel, message: string, ...args: unknown[]) => void;
  info: (message: string, ...args: unknown[]) => void;
  success: (message: string, ...args: unknown[]) => void;
  warn: (message: string, ...args: unknown[]) => void;
  error: (message: string, ...args: unknown[]) => void;
  debug: (message: string, ...args: unknown[]) => void;
  route: (message: string, ...args: unknown[]) => void;
  ipc: (message: string, ...args: unknown[]) => void;
  updater: (message: string, ...args: unknown[]) => void;
  perf: (message: string, ...args: unknown[]) => void;
  network: (message: string, ...args: unknown[]) => void;
  state: (message: string, ...args: unknown[]) => void;
  lifecycle: (message: string, ...args: unknown[]) => void;
}

interface UpdaterAPI {
  // Commands
  startDownload: () => void;
  installNow: () => void;
  checkForUpdates: () => void;
  // DEV ONLY: Test methods
  _testShowUpdate: () => void;
  _testSimulateDownload: () => void;
  // Event listeners
  onCheckingForUpdate: (callback: () => void) => () => void;
  onUpdateAvailable: (
    callback: (info: {
      version: string;
      releaseNotes: string | null;
      releaseDate: string;
    }) => void
  ) => () => void;
  onUpdateNotAvailable: (callback: (info: { version: string }) => void) => () => void;
  onDownloadProgress: (
    callback: (progress: {
      bytesPerSecond: number;
      percent: number;
      transferred: number;
      total: number;
    }) => void
  ) => () => void;
  onUpdateDownloaded: (
    callback: (info: {
      version: string;
      releaseNotes: string | null;
      releaseDate: string;
    }) => void
  ) => () => void;
  onUpdateError: (callback: (error: string) => void) => () => void;
}

declare interface Window {
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  debugAPI: DebugAPI;
  updaterAPI: UpdaterAPI;
}
