// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}

interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
}

type DebugLogLevel =
  | "info"
  | "success"
  | "warn"
  | "error"
  | "debug"
  | "route"
  | "ipc"
  | "updater"
  | "perf"
  | "network"
  | "state"
  | "lifecycle";

interface DebugAPI {
  log: (level: DebugLogLevel, message: string, ...args: unknown[]) => void;
  info: (message: string, ...args: unknown[]) => void;
  success: (message: string, ...args: unknown[]) => void;
  warn: (message: string, ...args: unknown[]) => void;
  error: (message: string, ...args: unknown[]) => void;
  debug: (message: string, ...args: unknown[]) => void;
  route: (message: string, ...args: unknown[]) => void;
  ipc: (message: string, ...args: unknown[]) => void;
  updater: (message: string, ...args: unknown[]) => void;
  perf: (message: string, ...args: unknown[]) => void;
  network: (message: string, ...args: unknown[]) => void;
  state: (message: string, ...args: unknown[]) => void;
  lifecycle: (message: string, ...args: unknown[]) => void;
}

interface UpdaterAPI {
  // Commands
  startDownload: () => void;
  installNow: () => void;
  checkForUpdates: () => void;
  // DEV ONLY: Test methods
  _testShowUpdate: () => void;
  _testSimulateDownload: () => void;
  // Event listeners
  onCheckingForUpdate: (callback: () => void) => () => void;
  onUpdateAvailable: (
    callback: (info: {
      version: string;
      releaseNotes: string | null;
      releaseDate: string;
    }) => void
  ) => () => void;
  onUpdateNotAvailable: (callback: (info: { version: string }) => void) => () => void;
  onDownloadProgress: (
    callback: (progress: {
      bytesPerSecond: number;
      percent: number;
      transferred: number;
      total: number;
    }) => void
  ) => () => void;
  onUpdateDownloaded: (
    callback: (info: {
      version: string;
      releaseNotes: string | null;
      releaseDate: string;
    }) => void
  ) => () => void;
  onUpdateError: (callback: (error: string) => void) => () => void;
}

// ─────────────────────────────────────────────────────────────────
// VRChat Types
// ─────────────────────────────────────────────────────────────────

interface VRChatAuthState {
  isAuthenticated: boolean;
  userId?: string;
  displayName?: string;
  avatarUrl?: string;
  requiresTwoFactor?: boolean;
  twoFactorMethods?: string[];
}

interface VRChatLoginCredentials {
  username: string;
  password: string;
}

interface VRChatTwoFactorRequest {
  method: "totp" | "emailotp" | "otp";
  code: string;
}

interface InviteRequest {
  userId: string;
  displayName: string;
  timestamp: number;
}

interface InviteResultData {
  result: "success" | "skipped" | "error";
  userId: string;
  displayName: string;
  message: string;
  timestamp: number;
}

interface InviterStats {
  totalProcessed: number;
  successful: number;
  skipped: number;
  errors: number;
  queueSize: number;
}

type InviterLogType =
  | "detect"
  | "invite"
  | "skip"
  | "error"
  | "auth"
  | "rate"
  | "queue"
  | "system";

interface InviterLogEntry {
  type: InviterLogType;
  message: string;
  timestamp: number;
  userId?: string;
  displayName?: string;
  // Translation support - if provided, renderer will translate
  i18nKey?: string;
  i18nParams?: Record<string, string | number>;
}

interface MonitorStatus {
  isRunning: boolean;
  logFilePath?: string;
  lastActivity?: number;
}

interface RateLimitSettings {
  inviteBatchCount: number;
  inviteBatchDelay: number;
  inviteDelayBetween: number;
  queueThreshold: number;
  queuePauseDelay: number;
}

interface DetectedPlayer {
  userId: string;
  displayName: string;
  timestamp: number;
}

interface VRChatGroup {
  id: string;
  name: string;
  shortCode: string;
  discriminator: string;
  description: string;
  iconUrl?: string;
  bannerUrl?: string;
  privacy: "default" | "private" | "public";
  ownerId: string;
  memberCount: number;
  onlineMemberCount?: number;
  membershipStatus?: string;
  isSearchable?: boolean;
  joinState?: string;
  tags?: string[];
  createdAt: string;
  updatedAt?: string;
}

// ─────────────────────────────────────────────────────────────────
// Invite History Types
// ─────────────────────────────────────────────────────────────────

interface InviteHistoryEntry extends InviteResultData {
  id: string;
}

interface InviteHistoryQueryOptions {
  limit?: number;
  offset?: number;
  search?: string;
  status?: "success" | "skipped" | "error";
}

interface InviteHistoryResponse {
  entries: InviteHistoryEntry[];
  total: number;
  hasMore: boolean;
}

interface InviteHistoryStats {
  total: number;
  successful: number;
  skipped: number;
  errors: number;
  lastInviteAt?: number;
}

interface InviteHistoryExportResult {
  success: boolean;
  path?: string;
  error?: string;
}

// ─────────────────────────────────────────────────────────────────
// Tray Types
// ─────────────────────────────────────────────────────────────────

interface TraySettings {
  minimizeToTray: boolean;
  showDesktopNotifications: boolean;
}

// ─────────────────────────────────────────────────────────────────
// Webhook Types
// ─────────────────────────────────────────────────────────────────

interface WebhookSettings {
  enabled: boolean;
  successUrl: string;
  warningUrl: string;
  errorUrl: string;
}

// ─────────────────────────────────────────────────────────────────
// Session Statistics Types
// ─────────────────────────────────────────────────────────────────

interface TimeBucket {
  startTime: number;
  playerCount: number;
  invitesSent: number;
  invitesSkipped: number;
  invitesError: number;
}

interface SessionData {
  id: string;
  startTime: number;
  endTime?: number;
  isActive: boolean;
  uniquePlayerIds: string[];
  totalPlayersDetected: number;
  totalInvitesSent: number;
  totalInvitesSkipped: number;
  totalInvitesError: number;
  timeBuckets: TimeBucket[];
}

interface SessionStatsQueryOptions {
  limit?: number;
  includeActive?: boolean;
}

interface PeakHourData {
  hour: number;
  avgPlayers: number;
}

interface SessionStatsResponse {
  sessions: SessionData[];
  activeSession?: SessionData;
  peakHours: PeakHourData[];
}

interface TrayAPI {
  getSettings: () => Promise<TraySettings>;
  setSettings: (settings: Partial<TraySettings>) => Promise<TraySettings>;
}

// ─────────────────────────────────────────────────────────────────
// Instance Monitor Types
// ─────────────────────────────────────────────────────────────────

type InstanceEventType = "world_enter" | "player_join" | "player_leave";

interface InstanceEvent {
  type: InstanceEventType;
  timestamp: number;
  worldName?: string;
  worldId?: string;
  instanceId?: string;
  region?: string;
  userId?: string;
  displayName?: string;
}

interface InstanceMonitorStatus {
  isRunning: boolean;
  logFilePath?: string;
  lastActivity?: number;
  currentWorld?: string;
  currentWorldId?: string;
}

interface InstanceMonitorStats {
  playersJoined: number;
  playersLeft: number;
  worldChanges: number;
}

interface InstanceWebhookSettings {
  enabled: boolean;
  webhookUrl: string;
}

type InstanceLogType = "world" | "join" | "leave" | "system";

interface InstanceLogEntry {
  type: InstanceLogType;
  message: string;
  timestamp: number;
  userId?: string;
  displayName?: string;
  worldName?: string;
  i18nKey?: string;
  i18nParams?: Record<string, string | number>;
}

interface InstanceMonitorAPI {
  // Monitor Control
  startMonitor: () => Promise<boolean>;
  stopMonitor: () => Promise<void>;
  getMonitorStatus: () => Promise<InstanceMonitorStatus>;
  getStats: () => Promise<InstanceMonitorStats>;
  resetStats: () => Promise<void>;

  // Log Buffer
  getLogBuffer: () => Promise<InstanceLogEntry[]>;
  clearLogBuffer: () => Promise<void>;

  // Settings
  getWebhookSettings: () => Promise<InstanceWebhookSettings>;
  setWebhookSettings: (settings: Partial<InstanceWebhookSettings>) => Promise<void>;
  resetWebhookSettings: () => Promise<InstanceWebhookSettings>;

  // Local User (for detecting own world changes)
  setLocalUser: (displayName: string | null) => Promise<void>;

  // VRChat Process (reuse from vrchatAPI)
  checkVRChatProcess: () => Promise<boolean>;

  // Event Listeners (return unsubscribe function)
  onMonitorStatusChanged: (callback: (status: InstanceMonitorStatus) => void) => () => void;
  onInstanceEvent: (callback: (event: InstanceEvent) => void) => () => void;
  onLogEntry: (callback: (entry: InstanceLogEntry) => void) => () => void;
  onStatsUpdated: (callback: (stats: InstanceMonitorStats) => void) => () => void;
}

interface VRChatAPI {
  // Authentication
  login: (credentials: VRChatLoginCredentials) => Promise<VRChatAuthState>;
  logout: () => Promise<void>;
  verify2FA: (request: VRChatTwoFactorRequest) => Promise<VRChatAuthState>;
  getAuthState: () => Promise<VRChatAuthState>;
  validateSession: () => Promise<boolean>;

  // Log Monitor
  startMonitor: () => Promise<boolean>;
  stopMonitor: () => Promise<void>;
  getMonitorStatus: () => Promise<MonitorStatus>;

  // Invite System
  addToQueue: (userId: string, displayName: string) => Promise<boolean>;
  clearQueue: () => Promise<void>;
  getStats: () => Promise<InviterStats>;
  getQueue: () => Promise<InviteRequest[]>;

  // VRChat Launcher
  launchVRChat: () => Promise<boolean>;

  // Settings
  getSettings: () => Promise<RateLimitSettings>;
  setSettings: (settings: Partial<RateLimitSettings>) => Promise<void>;
  resetSettings: () => Promise<RateLimitSettings>;

  // VRChat Path
  getVRChatPath: () => Promise<string | null>;
  setVRChatPath: (path: string) => Promise<boolean>;
  detectVRChatPath: () => Promise<string | null>;
  browseVRChatPath: () => Promise<string | null>;

  // Group Info
  getGroupInfo: () => Promise<VRChatGroup | null>;

  // Process Detection
  checkVRChatProcess: () => Promise<boolean>;
  getVRChatProcessStatus: () => Promise<boolean>;
  startProcessWatching: () => Promise<void>;
  stopProcessWatching: () => Promise<void>;

  // Invite History
  getHistory: (options?: InviteHistoryQueryOptions) => Promise<InviteHistoryResponse>;
  getHistoryStats: () => Promise<InviteHistoryStats>;
  exportHistoryCSV: () => Promise<InviteHistoryExportResult>;
  clearHistory: () => Promise<void>;

  // Session Statistics
  getSessionStats: (options?: SessionStatsQueryOptions) => Promise<SessionStatsResponse>;
  getActiveSession: () => Promise<SessionData | null>;
  clearSessionStats: () => Promise<void>;

  // Webhook Settings
  getWebhookSettings: () => Promise<WebhookSettings>;
  setWebhookSettings: (settings: Partial<WebhookSettings>) => Promise<void>;
  resetWebhookSettings: () => Promise<WebhookSettings>;

  // Language Settings
  getLanguage: () => Promise<"en" | "pl">;
  setLanguage: (lang: "en" | "pl") => Promise<void>;

  // Log Buffer
  getLogBuffer: () => Promise<InviterLogEntry[]>;
  clearLogBuffer: () => Promise<void>;

  // Event Listeners (return unsubscribe function)
  onAuthStateChanged: (callback: (state: VRChatAuthState) => void) => () => void;
  on2FARequired: (callback: (methods: string[]) => void) => () => void;
  onMonitorStatusChanged: (callback: (status: MonitorStatus) => void) => () => void;
  onPlayerDetected: (callback: (player: DetectedPlayer) => void) => () => void;
  onInviteResult: (callback: (result: InviteResultData) => void) => () => void;
  onStatsUpdated: (callback: (stats: InviterStats) => void) => () => void;
  onQueueUpdated: (callback: (queue: InviteRequest[]) => void) => () => void;
  onLogEntry: (callback: (entry: InviterLogEntry) => void) => () => void;
  onProcessStatusChanged: (callback: (isRunning: boolean) => void) => () => void;
  onSessionStatsUpdated: (callback: (session: SessionData | null) => void) => () => void;
}

declare interface Window {
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  debugAPI: DebugAPI;
  updaterAPI: UpdaterAPI;
  vrchatAPI: VRChatAPI;
  trayAPI: TrayAPI;
  instanceMonitorAPI: InstanceMonitorAPI;
}
